### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by sociedadeuniaosintrense** [VascoRibeiroPereira/SUS#6]
Criar um separador no dashboard com análise de dados de 2019 para a frente com hipotese de ir introduzindo os dados gerados mês a mês

**Comment by VascoRibeiroPereira** [comment]
Dashboard realizado. Os dados podem ser visualizados ao efetuar login na nossa app.
Algum dado adicional - ou um gráfico em especial - por favor comuniquem ou abram um issue para se realizar.
