### ISSUE TITLE
Criar uma base de dados

### ISSUE THREAD

**Issue by sociedadeuniaosintrense** [VascoRibeiroPereira/SUS#7]
Criar bases de dados MySQL para guardar as palavras passe dos utilizadores fora da aplicação de maneira a que estas estejam protegidas de sofrerem reset cada vez que se atualiza a aplicação

**Comment by VascoRibeiroPereira** [comment]
Matéria a ser estudada e a ser avaliada dentro de uma semana (até 2021/04/14)

**Comment by sociedadeuniaosintrense** [comment]
Surgiu um problema com a base de dados atual - as palavras pass sofrem reset para 12345 (palavra pass original ao fim de algum tempo). Este problema estará ligado ao facto da base de dados estar incluida no pacote da APP?

**Comment by VascoRibeiroPereira** [comment]
Este problema foi resolvido colocando a password original no código. O mesmo não será atualizado para o repositório por motivos de segurança.
Só passando para a conta do RStudio Server e RStudio Connect e pagando um serviço adicional conseguimos ter as passwords protegidas e recicladas ao nosso gosto.
Assim, fica o assunto "resolvido" na origem. O Issue será fechado sem se concretizar a base de dados para passes. Outras bases de dados (para informação) podem ser no entanto realizadas.
