### ISSUE TITLE
Tabela das contas - google sheet?

### ISSUE THREAD

**Issue by sociedadeuniaosintrense** [VascoRibeiroPereira/SUS#8]
Exportar as tabelas das contas para um sistema partilhado da SUS onde a APP possa ir buscar informação de forma a gerar informação gráfica para os dashboards a virem a ser criados.

Google sheet pode ser uma opção.

**Comment by VascoRibeiroPereira** [comment]
Realizado e a funcionar perfeitamente.

A conta gmail da SUS tem folhas de cálculo com as nossas contas atualizadas numa base mensal.
Também tem os automatismos e os centros de custo e rubricas.

Todas as folhas estão ligadas à nossa app.
